// Generated by https://quicktype.io

class DetalleVenta {
  int id;
  String nombre;
  double precio;
  double cantidad;
  double total;

  DetalleVenta({
    required this.id,
    required this.nombre,
    required this.precio,
    required this.cantidad,
    required this.total
  });
}
