// Generated by https://quicktype.io

class Venta {
  String id;
  String fecha;
  double total;
  double ganancias;

  Venta({
    required this.id,
    required this.fecha,    
    required this.total,
    required this.ganancias
  });
}
